### ISSUE TITLE
[Feature Request] Option to change color/positioning on inventory icon

### ISSUE THREAD

**Issue by Kyriella** [robrichardson13/inventory-count#1]
I'd like to see the option to change the text color (using ARGB like other RuneLite plugins support) and the option to choose the positioning of the number on the inventory icon (center, top-left, top-right, etc.) with the "Render on inventory icon" option enabled. Specifically, I'd like to be able to have the number horizontally and vertically centered on the inventory icon.

Nice, simple plugin! Thanks for making it!

**Comment by zenrion** [comment]
I can take a look at this when I have some more time.

**Comment by zenrion** [comment]
Feature currently up for review: https://github.com/robrichardson13/inventory-count/pull/7

**Comment by zenrion** [comment]
@Kyriella The feature has been merged and will be included in version `1.1.0` once it is approved by the Runelite team.

**Comment by Kyriella** [comment]
Thank you so much! I'm looking forward to it!
