### ISSUE TITLE
[Bug] Icon no longer appearing after update

### ISSUE THREAD

**Issue by Nick2bad4u** [robrichardson13/inventory-count#2]
Example:
![image](https://github.com/user-attachments/assets/43e35aa6-b7a8-4d39-b2e0-3194dea0b710)

**Comment by mitchmorgan36** [comment]
Plugin no longer works for me either. I tested modern resizable, classic resizable, and fixed mode but it nothing I tried makes it show up.

**Comment by garygulman** [comment]
I use this simple plugin sooo much it turns out lol. please update :)

**Comment by Nick2bad4u** [comment]
Hopefully the dev sees this. He's been inactive on GitHub since Jan 27.

It would be a bummer... That is what's currently happening with the Wiki Bank Tag Generator plugin now. Dev is MIA and it's broken.

**Comment by CovetousLife** [comment]
@robrichardson13

**Comment by zenrion** [comment]
@robrichardson13 I've fixed the issue and submitted a PR. Please take a look when you have a chance.

**Comment by Nick2bad4u** [comment]
> @robrichardson13 I've fixed the issue and submitted a PR. Please take a look when you have a chance.

Well done, thanks mate.

**Comment by robrichardson13** [comment]
Fixed in https://github.com/robrichardson13/inventory-count/pull/5

Submitting version update to the plugin hub.
