### ISSUE TITLE
Broken in latest update

### ISSUE THREAD

**Issue by Scraxer** [robrichardson13/inventory-count#3]
Hey there, plugin doesn't appear to be functioning in this latest build.
Also curious, I've made this plugin and want to know if you'd be interested in building this out further?

https://github.com/Scraxer/Inventory-Free-Slots

Cheers

**Comment by zenrion** [comment]
The display issue has been fixed in version 1.0.2.
As for the collaboration, I am only looking to maintain this plugin.
Perhaps you can reach out to @robrichardson13 directly about if he wants to collaborate?

I'll be closing this issue since the bug has been fixed.
